let events = [
  //---Tháng 3/2026---//
  { 
    id: 1, 
    title: "Concert Blackpink: World Tour",
    desc: "Live concert Blackpink", 
    category: "Nhạc sống", 
    date: "2026-03-21", 
    location: "Sân Mỹ Đình", 
    price: "2.500.000đ", 
    hot: true, 
    img: "https://www.instagram.com/p/DMNbY9uMYHY/" 
  },
  {
    id: 2,
    title: "Workshop: Art Therapy - Vẽ Pastel",
    desc: "Trải nghiệm vẽ pastel",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-21",
    location: "EventHub Studio",
    price: "Miễn phí",
    hot: false,
    img : "",
  },
  {
    id: 3,
    title: "Vietnam Tech Expo: AI & Future",
    desc: "Triển lãm công nghệ AI",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-05",
    location: "VNU Innovation Hub",
    price: "Miễn phí",
    hot: false,
    img: "",
  },
  {
    id: 4,
    title: "Giải Bóng đá MB Hanoi Cup 2026",
    desc: "Giải bóng đá hấp dẫn nhất Hà Nội",
    category: "Thể thao",
    date: "2026-03-25",
    location: "Sân Mỹ Đình",
    price: "200.000đ",
    hot: false,
    img: "mbhanoicup.jpeg"
  },
  {
    id: 5,
    title: "Đêm Nhạc Trịnh: Nối Vòng Tay Lớn",
    desc: "Đêm nhạc tưởng nhớ Trịnh Công Sơn",
    category: "Nhạc sống",
    date: "2026-03-28",
    location: "Nhà hát Lớn Hà Nội",
    price: "800.000đ",
    hot: false,
    img: "trinhcongson.jpeg"
  },
  {
    id: 6,
    title: "Tech Talk: Web3 & Blockchain",
    desc: "Hội thảo về Web3 và Blockchain",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-12",
    location: "Quận 1, TP.HCM",
    price: "150000đ",
    hot: false,
    img: "",
  },
  {
    id: 7,
    title: "VNU Fintech Forum 2026",
    desc: "Diễn đàn Fintech hàng đầu Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-05",
    location: "VNU-IS Hall",
    price: "Miễn phí",
    hot: false,
    img: "",
  },
  {
    id: 8,
    title: "Vietnam Cosplay Festival 2026",
    desc: "Lễ hội cosplay lớn nhất Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-10",
    location: "Công viên Thống Nhất",
    price: "120.000đ",
    hot: false,
    img: "anhtraisayhi.jpeg"
  },
  {
    id: 9,
    title: "Marathon Vì Cộng Đồng - UpRace",
    category: "Thể thao",
    date: "2026-03-15",
    location: "Hồ Gươm",
    price: "Miễn phí",
    hot: false,
    img: "marathon.jpeg"
  },
  {
    id: 10,
    title: "Vietnam Fintech Summit 2026",
    desc: "Hội nghị thượng đỉnh Fintech Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-15",
    location: "Lotte Center Hà Nội",
    price: "500.000đ",
    hot: false,
    img: "",
  },
  {
    id: 11,
    title: "VCS League Championship (LOL)",
    desc: "Giải đấu Liên Minh Huyền Thoại lớn nhất Việt Nam",
    category: "Thể thao",
    date: "2026-03-30",
    location: "GG Stadium",
    price: "100.000đ",
    hot: false,
    img: "vcs.jpeg"
  },
  {
    id: 12,
    title: "Triển lãm Vietnam Auto Expo",
    desc: "Triển lãm ô tô lớn nhất Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-20",
    location: "SECC Quận 7",
    price: "50.000đ",
    hot: false,
    img: "autoexpo.jpeg",
  },
  {
    id: 13,
    title: "Startup Pitch Night: Gen Z Innovators",
    desc: "Sự kiện pitching dành cho startup Gen Z",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-14",
    location: "Hà Nội Hub",
    price: "Miễn phí",
    hot: false,
    img: "",
  },
  {
    id: 14,
    title: "Jazz Under The Stars: Moonlight",
    category: "Nhạc sống",
    date: "2026-03-14",
    location: "Skyline Bar",
    price: "350.000đ",
    hot: false,
    img: "jazz.jpeg"
  },
  {
    id: 15,
    title: "Lễ Hội Ánh Sáng: Heritage Night",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-14",
    location: "Phố đi bộ",
    price: "150.000đ",
    hot: false,
    img: "lehoianhsang.jpeg"
  },
  {
    id: 16,
    title: "Giải Cờ Vua Quốc Tế HDBank",
    desc: "Giải cờ vua quốc tế hấp dẫn nhất Việt Nam",
    category: "Thể thao",
    date: "2026-03-18",
    location: "Khách sạn Melia Hà Nội",
    price: "Miễn phí",
    hot: false,
    img: "cocua.jpeg"
  },
  {
    id: 17,
    title: "K-Pop Festa Summer 2026",
    desc: "Lễ hội K-Pop lớn nhất Việt Nam",
    category: "Nhạc sống",
    date: "2026-06-20",
    location: "Sân Quần Ngựa",
    price: "1.800.000đ",
    hot: false,
    img: "kpopfesta.jpeg"
  },
  {
    id: 18,
    title: "Workshop: Nghệ thuật Gốm Bát Tràng",
    desc: "Trải nghiệm làm gốm truyền thống",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-21",
    location: "Bát Tràng Studio",
    price: "450000đ",
    hot: false,
  },
  {
    id: 19,
    title: "Ngày hội Sách và Văn hóa Đọc",
    desc: "Sự kiện sách lớn nhất Hà Nội",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-22",
    location: "Đường Sách 19/12",
    price: "Miễn phí",
    hot: false,
  },
  {
    id: 20,
    title: "VNU Data Science Seminar",
    desc: "Hội thảo khoa học dữ liệu tại VNU",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-26",
    location: "VNU Sunwah",
    price: "Miễn phí",
    hot: false,
    img: "vba.jpeg",
    hot: false,
  },
  {
    id: 21,
    title: "Rap Việt Star",
    desc: "Giải rap Việt Nam",
    category: "Nhạc sống",
    date: "2026-03-28",
    location: "SECC Quận 7",
    price: "1.200.000đ",
    hot: true,
    img: "vba.jpeg"
  },
  {
    id: 22,
    title: "Sáng sớm cùng Yoga Heritage",
    desc: "Buổi tập yoga ngoài trời tại Heritage",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-01",
    location: "Bờ Hồ Gươm",
    price: "Miễn phí",
    hot: false,
    img: "yoga.jpeg"
  },
  {
    id: 23,
    title: "Coffee Talk: AI in Visual Art",
    desc: "Buổi trò chuyện về AI trong nghệ thuật thị giác",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-01",
    location: "The Coffee House",
    price: "50.000đ",
    hot: false,
    img: "coffeetalk.jpeg"
  },
  {
    id: 24,
    title: "Workshop: Kỹ Năng Tư Duy Phản Biện",
    desc: "Trải nghiệm kỹ năng tư duy phản biện",
    category: "Tham quan & Trải nghiệm",
    date: "2026-03-02",
    location: "The Coffee House",
    price: "80.000đ",
    hot: false,
    img: "workshop.jpeg"
  },
  {
    id: 25,
    title: "Concert: Anh Trai Say Hi (Live)",
    desc: "Live concert của Anh Trai Say Hi",
    category: "Nhạc sống",
    date: "2026-03-02",
    time: "19:00",
    location: "Sân Mỹ Đình",
    price: "1.200.000đ",
    hot: true,
    img: "anhtraisayhi.jpeg"
  },
  {
    id: 53,
    title: "GreenGreen Cortis",
    desc: "Live concert",
    category: "Nhạc sống",
    date: "2026-04-20",
    time: "19:00",
    location: "Vincom center",
    price: "1.500.000đ",
    hot: true,
    img: "cortis.jpg"
  },
  {
    id: 26,
    title: "Arirang World Tour",
    desc: "Live concert Arirang",
    category: "Nhạc sống",
    date: "2026-03-08",
    location: "Sân vận động EL Campin",
    price: "1.000.000đ",
    hot: true,
    img: "arirang.jpeg"
  },
  //---Tháng 4/2026---//
  {
    id: 27,
    title: "VNU-IS Fintech Summit 2026",
    desc: "Hội nghị thượng đỉnh Fintech tại VNU-IS",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-02",
    location: "Hội trường Sunwah",
    price: "Miễn phí",
    hot: false,
    img: "vnuis.jpeg"
  },
  {
    id: 28,
    title: "Live Acoustic: Soul of Hanoi",
    desc: "Đêm nhạc acoustic tại Hà Nội",
    category: "Nhạc sống",
    date: "2026-04-03",
    location: "Tranquil Books & Coffee",
    price: "150.000đ",
    hot: false,
    img: "acoustic.jpeg"
  },
  {
    id: 29,
    title: "VnExpress Marathon Hanoi Midnight",
    desc: "Marathon chạy đêm tại Hà Nội",
    category: "Thể thao",
    date: "2026-04-05",
    location: "Hồ Hoàn Kiếm",
    price: "450.000đ",
    hot: false,
    img: "marathon.jpeg"
  },
  {
    id: 30,
    title: "Triển lãm Xe độ & Phụ kiện",
    desc: "Triển lãm xe độ và phụ kiện ô tô",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-05",
    location: "TT Triển lãm I.C.E",
    price: "100.000đ",
    hot: false,
    img: "workshop.jpeg"
  },
  {
    id: 31,
    title: "Workshop Digital Marketing Performance",
    desc: "Trải nghiệm kỹ năng Digital Marketing Performance",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-07",
    location: "Coworking Space Q1",
    price: "200.000đ",
    hot: false,
    img: "",
  },
  {
    id: 32,
    title: "Lễ hội Văn hóa Nhật Bản",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-10",
    location: "Công viên Thống Nhất",
    price: "50.000đ",
    hot: false,
    img: "lehoianhsang.jpeg"
  },
  {
    id: 33,
    title: "Concert Sơn Tùng M-TP: Sky Tour",
    category: "Nhạc sống",
    date: "2026-04-11",
    location: "Sân Mỹ Đình",
    price: "1.500.000đ",
    hot: false,
    img: "sontung.jpeg"
  },
  {
    id: 34,
    title: "Hội chợ Sách Quốc tế Việt Nam",
    category: "Hội thảo & Workshop",
    date: "2026-04-12",
    location: "Hoàng Thành Thăng Long",
    price: "Miễn phí",
    hot: false,
    img: "",
  },
  {
    id: 35,
    title: "FPT Tech Day: Blockchain World",
    desc: "",
    category: "Hội thảo & Workshop",
    date: "2026-04-14",
    location: "FPR Tower",
    price: "Miễn phí",
    hot: false,
    img: "https://media.licdn.com/dms/image/v2/D4E22AQG_cd3EOlRseA/feedshare-shrink_2048_1536/feedshare-shrink_2048_1536/0/1731594519669?e=2147483647&v=beta&t=zgHTpugMifIQQ0K7Y1PtTizBTgQ2e2sjsx03fSZxbyw",
  },
  {
    id: 36,
    title: "Workshop: Cắm Hoa Ikebana Nhật Bản",
    desc: "Trải nghiệm nghệ thuật cắm hoa Ikebana",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-15",
    location: "Tiệm Hoa Xinh",
    price: "350.000đ",
    hot: false,
    img: "cammhoa.jpeg"
  },
  {
    id: 37,
    title: "Giải Bóng rổ VBA 3x3 Prime",
    desc: "Giải bóng rổ 3x3 hấp dẫn nhất Việt Nam",
    category: "Thể thao",
    date: "2026-04-17",
    location: "Nhà thi đấu Thanh Xuân",
    price: "120.000đ",
    hot: false,
    img: "https://i.ytimg.com/vi/296V9663Vng/maxresdefault.jpg"
  },
  {
    id: 38,
    title: "TEDx VNU-IS: Beyond Limits",
    desc: "",
    category: "Hội thảo & Workshop",
    date: "2026-04-18",
    location: "VNU International School",
    price: "300.000đ",
    hot: false,
    img:"https://th.bing.com/th/id/R.03a15486b49fa9151e9f32b42acfee05?rik=7ppGXnifs9R1mQ&riu=http%3a%2f%2fgreenideahouse.com%2fwp-content%2fuploads%2f2014%2f08%2fBeyondLimits-3.jpg&ehk=gmvR5pzCUZnfc33b9lc6kBwb6upAn9ykLwypHRSjsj0%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 39,
    title: "Hài Độc Thoại: Saigon Comic Night",
    category: "Sân khấu & Nghệ thuật",
    date: "2026-04-18",
    location: "Rotunda Bar",
    price: "250.000",
    hot: false,
    img: "https://scontent.fhan18-1.fna.fbcdn.net/v/t39.30808-6/571238450_1371377057969678_1824108918891925736_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=7e0d18&_nc_eui2=AeGqRAr7-3bpvg2JOW8O7LH0rL1NQRiqYlmsvU1BGKpiWS4KCeD1hhvDn60MMW6rC07mL9iSvR2Z00KQgeO12NcT&_nc_ohc=h9ak4ZLAu40Q7kNvwEPHjdO&_nc_oc=Adpk6YDCvCY_m7acpylgpsfqunF2-Kq2K-ZepyWvCXOSc8TEYA2y0TE6w1YTFlAAgLk&_nc_zt=23&_nc_ht=scontent.fhan18-1.fna&_nc_gid=zUo7KZR-sMJAbdCm9aI9Kw&_nc_ss=7a3a8&oh=00_Af0Cxtt-oJ6HcNZ7y0Pty2CJ70yyoqtrzsfa-iWK9EMNZg&oe=69D6B8AB",
  },
  {
    id: 40,
    title: "Workshop: Tinh hoa ẩm thực Sushi",
    desc: "Trải nghiệm kỹ năng nấu ăn Sushi",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-19",
    location: "Học viện Ẩm thực",
    price: "500.000đ",
    hot: false,
    img: "https://sushiworld.com.vn/wp-content/uploads/2023/05/1.jpg"
  },
  {
    id: 41,
    title: "Talkshow: AI & Ethical Dilemmas",
    desc: "Buổi trò chuyện về AI và các vấn đề đạo đức",
    category: "Hội thảo & Workshop",
    date: "2026-04-21",
    location: "Hội trường Sunwah",
    price: "200.000đ",
    hot: false,
    img: "https://tse4.mm.bing.net/th/id/OIP.le0iSvXTSAAYOakI9doYKQHaLH?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: 42,
    title: "Hội thảo: Săn học bổng Ivy League",
    desc: "Hội thảo về cơ hội học bổng tại các trường đại học Ivy League",
    category: "Hội thảo & Workshop",
    date: "2026-04-22", time: "8:30",
    location: "Khách sạn Daewoo",
    price: "Miễn phí",
    hot: false,
    img: "https://scientia.edu.vn/wp-content/uploads/2024/08/hoc-bong-ivy-league.jpg",
  },
  {
    id: 43,
    title: "Workshop: Vẽ Tranh Acrylic Summer",
    desc: "Trải nghiệm vẽ tranh acrylic mùa hè",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-25", time: "14:30",
    location: "Art Center",
    price: "400.000đ",
    hot: false,
  },
  {
    id: 44,
    title: "Hay Glamping Music Festival",
    desc: "Lễ hội âm nhạc ngoài trời tại Hay Glamping",
    category: "Nhạc sống",
    date: "2026-04-25", time: "16:00",
    location: "EcoPark",
    price: "850.000đ",
    hot: false,
    img: "https://hololab.vn/wp-content/uploads/2023/12/Le-hoi-HAY-Glamping-Music-Festival-1024x1024.jpeg"
  },
  {
    id: 45,
    title: "Triển lãm: Di sản Sơn mài Việt",
    desc: "Triển lãm nghệ thuật sơn mài truyền thống Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-26", time: "9:00",
    location: "Bảo tàng Mỹ thuật",
    price: "40.000đ",
    hot: false,
    img: "https://tse4.mm.bing.net/th/id/OIP.cy5yy7ZYgedBctTDho13IwHaER?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: 46,
    title: "Workshop: Nghệ thuật Latte Art",
    desc: "Trải nghiệm kỹ năng pha chế cà phê với nghệ thuật latte art",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-27", time: "15:00",
    location: "Aha Coffee Training",
    price: "300.000đ",
    hot: false,
    img: "https://tse3.mm.bing.net/th/id/OIP.rEDjZDqIOdGPBeV689XSBQHaEk?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: 47,
    title: "Street Food Festival: Việt Nam vị ngon",
    desc: "Lễ hội thực phẩm đường phố với các món ăn đặc sản Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-29", time: "17:00",
    location: "Phố đi bộ Hoàn Kiếm",
    price: "Vào cửa tự do",
    hot: false,
    img: "",
  },
  {
    id: 48,
    title: "Concert Tổ quốc 30/4 - 1/5",
    desc: "Live concert Tổ quốc",
    category: "Nhạc sống",
    date: "2026-04-30",
    location: "Quảng trường Ba Đình",
    price: "Miễn phí",
    hot: true,
    img: "concerttoquoc.jpg"
  },
  {
    id: 49,
    title: "Trải nghiệm: Đạp xe đêm Hà Nội",
    desc: "Trải nghiệm đạp xe đêm quanh Hồ Gươm",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-30", time: "22:00",
    location: "Nhà hát Lớn",
    price: "150.000đ",
    hot: false,
    img: "https://tse1.mm.bing.net/th/id/OIP.iUVDH5ADwrk8-5HtAi6WEwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: 50,
    title: "Seminar: Fintech & Cybersecurity",
    desc: "Hội thảo về Fintech và An ninh mạng",
    category: "Hội thảo & Workshop",
    date: "2026-04-08", time: "9:00",
    location: "VNU-IS Building",
    price: "Miễn phí",
    hot: false,
    img: "https://tse4.mm.bing.net/th/id/OIP.7n9s8Xo2l3m1e5j6qj8c9QHaEo?rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: 51,
    title: "Giải Tennis Hà Nội Open 2026",
    desc: "Giải tennis chuyên nghiệp tại Hà Nội",
    category: "Thể thao",
    date: "2026-04-13", time: "7:30",
    location: "Sân Quần Ngựa",
    price: "200.000đ",
    hot: false,
    img: "tennis.jpeg",
  },
  {
    id: 52,
    title: "Tham quan thuỷ cung",
    desc: "Trải nghiệm thế giới dưới nước tại thuỷ cung lớn nhất Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-16", time: "8:00",
    location: "Lotte Tây Hồ",
    price: "250.000đ",
    hot: false,
    img: "thuysinh.jpeg",
  },
  { id: 53, 
    title: "GreenGreen Cortis", 
    desc: "Đêm nhạc GreenGreen Cortis với sự tham gia của nhiều nghệ sĩ nổi tiếng",
    category: "Nhạc sống",
    date: "2026-04-20", time: "18:00", 
    location: "Vincom Center", 
    color: "bg-red-600", 
    price: "300.000đ",
    hot: false,
  },
  { 
    id: 54, 
    title: "Yoga Sunset: Khoảnh khắc hoàng hôn",
    desc: "Buổi tập yoga ngoài trời ngắm hoàng hôn tại công viên",
    category: "Tham quan & Trải nghiệm", 
    date: "2026-04-23", time: "17:30", 
    location: "West Lake Park", 
    color: "bg-orange-300", 
    price: "150.000đ", 
    hot: false,
  },
  { 
    id: 55, 
    title: "Jazz Classic: Blue Note Night", 
    desc: "Đêm nhạc jazz kinh điển với sự tham gia của nhiều nghệ sĩ nổi tiếng",
    category: "Nhạc sống",
    date: "2026-04-28", time: "20:00", 
    location: "Cool Cat Club", 
    color: "bg-indigo-900", 
    price: "400.000đ",
    hot: false,
  },
  { 
    id: 56, 
    title: "Saigon Garage Sale: Tái chế & Đồ cũ", 
    desc: "Sự kiện mua bán đồ cũ và tái chế tại Sài Gòn",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-04", time: "09:00", 
    location: "Quận 2, HCM", color: "bg-yellow-600", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 57, 
    title: "Trải nghiệm: Khám phá Vũ trụ 3D", 
    desc: "Trải nghiệm khám phá vũ trụ qua công nghệ 3D tại nhà kính thiên văn",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-09", time: "19:00", 
    location: "Hanoi Planetarium", 
    color: "bg-blue-900", 
    price: "80.000đ",
    hot: true,
  },
  { 
    id: 58, 
    title: "Workshop: Sáng tạo Nến Thơm", 
    desc: "Học cách tạo ra những chiếc nến thơm độc đáo",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-14", time: "14:00", 
    location: "Scent Lab", 
    color: "bg-rose-200", 
    price: "380.000đ",
    hot: false,
  },
  { 
    id: 59, 
    title: "Giải Cờ vua Sinh viên VNU", 
    desc: "Giải cờ vua dành cho sinh viên VNU với sự tham gia của nhiều trường đại học",
    category: "Thể thao",
    date: "2026-04-22", time: "08:00", 
    location: "VNU-IS Library", 
    color: "bg-zinc-800", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 60, 
    title: "Bootcamp: Python for Data Analysis",
    desc: "Khóa học ngắn hạn về Python cho phân tích dữ liệu",
    category: "Hội thảo & Workshop", 
    date: "2026-04-15", time: "18:00", 
    location: "Online via MS Teams", 
    color: "bg-yellow-500", 
    price: "Miễn phí",
    hot: false, 
  },
  { 
    id: 61, 
    title: "Lễ hội Cosplay: Manga Festival",
    desc: "Lễ hội cosplay với chủ đề manga và anime",
    category: "Tham quan & Trải nghiệm", 
    date: "2026-04-26", time: "09:00", 
    location: "AEON Mall Long Biên", 
    color: "bg-purple-600", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 62, 
    title: "Hội thảo: Startup Gen Z & AI", 
    desc: "Hội thảo về startup thế hệ Gen Z và trí tuệ nhân tạo",
    category: "Hội thảo & Workshop",
    date: "2026-04-11", time: "14:00", 
    location: "Hanoi Hub", 
    color: "bg-emerald-400", 
    price: "100.000đ",
    hot: false,
  },
  { 
    id: 63, 
    title: "Đêm nhạc: Rock Việt - Bùng nổ", 
    desc: "Đêm nhạc rock Việt Nam với sự tham gia của nhiều nghệ sĩ nổi tiếng",
    category: "Nhạc sống",
    date: "2026-04-18", time: "19:00", 
    location: "Sân vận động Tự Do", 
    color: "bg-black", 
    price: "300.000đ",
    hot: true,
  },
  { 
    id: 64, 
    title: "Workshop: Pottery & Decor", 
    desc: "Học cách tạo ra những chiếc nến thơm độc đáo",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-05", time: "10:00", 
    location: "Bát Tràng", 
    color: "bg-orange-200", 
    price: "450.000đ",
    hot: false,
  },
  { 
    id: 65, 
    title: "Giải Bơi lội Thanh niên 2026",
    desc: "Giải đấu bơi lội dành cho thanh niên năm 2026",
    category: "Thể thao",
    date: "2026-04-30", time: "07:00", 
    location: "Cung dưới nước Mỹ Đình", 
    color: "bg-blue-300", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 66, 
    title: "Khám phá: Landscape Photography Tour", 
    desc: "Khám phá cảnh quan thiên nhiên qua ống kính máy ảnh",
    category: "Tham quan & Trải nghiệm",
    date: "2026-04-12", time: "05:00", 
    location: "Vườn quốc gia Ba Vì", 
    color: "bg-green-700", 
    price: "600.000đ",
    hot: false,
  },
  // --- THÁNG 5/2026 ---
  { 
    id: 67, 
    title: "Lễ hội Quốc tế Lao động Việt-Xô", 
    desc: "Lễ hội kỷ niệm ngày Quốc tế Lao động với sự tham gia của các nghệ sĩ và đoàn nghệ thuật từ Việt Nam và Nga",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-01", time: "09:00", 
    location: "Công viên Thống Nhất", 
    color: "bg-red-500", 
    price: "Miễn phí",
    hot: true,
  },
  { 
    id: 68, 
    title: "Bootcamp: Data Science & AI", 
    desc: "Khóa học ngắn hạn về Data Science và AI",
    category: "Hội thảo & Workshop",
    date: "2026-05-02", time: "14:00", 
    location: "VNU-IS", 
    color: "bg-blue-600", 
    price: "Miễn phí",
    hot: false,
   },
  { 
    id: 69, 
    title: "Những Thành Phố Mơ Màng: Indie Night", 
    desc: "Biểu diễn âm nhạc indie tại nhà hát Hòa Bình",
    category: "Giải trí",
    date: "2026-05-03", time: "19:00", 
    location: "Nhà hát Hòa Bình", 
    color: "bg-emerald-300", 
    price: "500.000đ",
    hot: true,
  },
  { 
    id: 70, 
    title: "Giải Marathon TP.HCM (HCMC Run)", 
    desc: "Giải marathon tại TP.HCM",
    category: "Thể thao",
    date: "2026-05-04", time: "04:00", 
    location: "Quận 1", 
    color: "bg-blue-500", 
    price: "600.000đ",
    hot: false,
  },
  { 
    id: 71, 
    title: "Hội thảo: AI Transform in Fintech", 
    desc: "Hội thảo về ứng dụng AI trong tài chính",
    category: "Hội thảo & Workshop",
    date: "2026-05-06", time: "09:00", 
    location: "Lotte Center", 
    color: "bg-indigo-400", 
    price: "300.000đ",
    hot: false,
  },
  { 
    id: 72, 
    title: "Workshop: Macaron Making Masterclass", 
    desc: "Khóa học làm bánh macaron chuyên nghiệp",
    category: "Hội thảo & Workshop",
    date: "2026-05-08", time: "15:00", 
    location: "Bakery School", 
    color: "bg-pink-200", 
    price: "450.00０đ",
    hot: false,
  },
  { 
    id: 73, 
    title: "Đại hội Thể thao Sinh viên VNU", 
    desc: "Đại hội thể thao dành cho sinh viên VNU",
    category: "Thể thao",
    date: "2026-₀5-1₀", time: "₀7:₀₀", 
    location: "Sân vận động Bách Khoa", 
    color: "bg-yellow-5₀₀", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 74, 
    title: "Workshop: Kỹ năng Thuyết trình AI", 
    desc: "Khóa học nâng cao kỹ năng thuyết trình về AI",
    category: "Hội thảo & Workshop",
    date: "2026-05-12", time: "18:30", 
    location: "Toong Coworking", 
    color: "bg-purple-400", 
    price: "150.000đ", 
    hot: false,
  },
  { 
    id: 75, 
    title: "Triển lãm: VIETNAM ICTCOMM 2026", 
    desc: "Triển lãm công nghệ thông tin và truyền thông lớn nhất Việt Nam",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-15", time: "09:00", 
    location: "NIC Hòa Lạc", 
    color: "bg-cyan-500", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 76, 
    title: "Phòng trà: Tình ca Trịnh Công Sơn", 
    desc: "Đêm nhạc tình ca Trịnh Công Sơn tại phòng trà Không Tên",
    category: "Nhạc sống",
    date: "2026-05-16", 
    time: "20:00", 
    location: "Phòng trà Không Tên", 
    color: "bg-amber-600", 
    price: "600.000đ", 
    hot: false,
  },
  { 
    id: 77, 
    title: "Workshop: Vẽ Henna & Boho Style", 
    desc: "Trải nghiệm vẽ henna và phong cách boho",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-17", 
    time: "14:00", 
    location: "Bohemian Cafe", 
    color: "bg-orange-400", 
    price: "200.000đ",
    hot: false, 
  },
  { 
    id: 78, 
    title: "Giải Cầu lông mở rộng 2026", 
    desc: "Giải đấu cầu lông mở rộng",
    category: "Thể thao",
    date: "2026-05-19", 
    time: "08:00", 
    location: "CLB thể thao Hoàn Kiếm", 
    color: "bg-blue-400", 
    price: "100.000đ", 
    hot: false,
  },
  { 
    id: 79, 
    title: "Vietnam Marketing Summit 2026", 
    desc: "Hội thảo marketing tại Việt Nam",
    category: "Hội thảo & Workshop",
    date: "2026-05-20", 
    time: "09:00", 
    location: "JW Marriott Hanoi", 
    color: "bg-slate-800", 
    price: "2.000.000đ", 
    hot: false,
  },
  { 
    id: 80, 
    title: "Workshop: Terrarium Art Workshop", 
    desc: "Khóa học nghệ thuật terrarium",
    category: "Hội thảo & Workshop",
    date: "2026-05-22", 
    time: "10:00", 
    location: "Green Garden", 
    color: "bg-green-400", 
    price: "350.000đ", 
    hot: false,
  },
  { 
    id: 81, 
    title: "Show: Fashion Walk Summer Vibe", 
    desc: "Chương trình thời trang mùa hè",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-25", 
    time: "19:30", 
    location: "Phố đi bộ", 
    color: "bg-fuchsia-400", 
    price: "Vào cửa tự do", 
    hot: false,
  },
  { 
    id: 82, 
    title: "Giải Đua thuyền rồng Hồ Tây", 
    desc: "Giải đấu thuyền rồng",
    category: "Thể thao",
    date: "2026-05-28", 
    time: "08:00", 
    location: "Hồ Tây", 
    color: "bg-red-400", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 83, 
    title: "VNU Seminar: Tâm lý học Sinh viên", 
    desc: "Hội thảo về tâm lý học dành cho sinh viên VNU",
    category: "Hội thảo & Workshop",
    date: "2026-05-25", time: "14:00", 
    location: "VNU Library Hall", 
    color: "bg-teal-500", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 84, 
    title: "Workshop: DIY Leather Craft", 
    desc: "Khóa học thủ công da thủ công",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-27", 
    time: "15:00", 
    location: "Craft Shop", 
    color: "bg-stone-500", 
    price: "550.000đ",
    hot: false, 
  },
  { 
    id: 85, 
    title: "Concert: Chillies - Trên Những Đám Mây", 
    desc: "Đêm nhạc của ban nhạc Chillies",
    category: "Nhạc sống",
    date: "2026-05-29", 
    time: "19:00", 
    location: "Nhà thi đấu Quân khu 7", 
    color: "bg-sky-400", 
    price: "700.000đ", 
    hot: false,
  },
  { 
    id: 86, 
    title: "Lễ bế giảng năm học VNU-IS", 
    desc: "Lễ bế giảng năm học dành cho sinh viên VNU-IS",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-31", 
    time: "08:00", 
    location: "Hội trường lớn VNU", 
    color: "bg-indigo-500", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 87, 
    title: "Workshop: Tarot & Crystal Healing", 
    desc: "Khóa học tarot và chữa lành bằng đá",
    category: "Hội thảo & Workshop",
    date: "2026-05-05", 
    time: "18:00", 
    location: "Mystic House", 
    color: "bg-purple-900", 
    price: "300.000đ",
    hot: false,
  },
  { 
    id: 88, 
    title: "Giải Bóng đá mini Business Cup", 
    desc: "Giải đấu bóng đá mini",
    category: "Thể thao",
    date: "2026-05-09", 
    time: "16:00", 
    location: "Sân bóng cỏ nhân tạo", 
    color: "bg-green-500", 
    price: "150.000đ",
    hot: false, 
  },
  { 
    id: 89, 
    title: "Lớp học: K-pop Dance Cover", 
    desc: "Khóa học khiêu vũ K-pop",
    category: "Tham quan & Trải nghiệm",
    date: "2026-05-07", 
    time: "19:00", 
    location: "Dance Studio Q3", 
    color: "bg-yellow-400", 
    price: "120.000đ",
    hot: false,
  },
  { 
    id: 90, 
    title: "Hội thảo: Đầu tư Crypto cho người mới", 
    desc: "Hội thảo về đầu tư crypto cho người mới",
    category: "Hội thảo & Workshop",
    date: "2026-05-21", time: "14:00", 
    location: "Hội sở Ngân hàng số", 
    color: "bg-blue-900", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 91, 
    title: "Skincare Masterclass by Shiseido", 
    desc: "Khóa học chăm sóc da của Shiseido",
    category: "Hội thảo & Workshop",
    date: "2026-05-26", time: "15:00", 
    location: "Showroom Mỹ phẩm", 
    color: "bg-pink-300", 
    price: "Miễn phí", 
    hot: false,
  },
  { 
    id: 92, 
    title: "Đêm nhạc Jazz Mùa hạ: Sunny", 
    desc: "Đêm nhạc Jazz Mùa hạ",
    category: "Nhạc sống",
    date: "2026-05-30", 
    time: "20:30", 
    location: "Bình Minh Jazz Club", 
    color: "bg-gray-800", 
    price: "450.000đ",
    hot: false,
  },
  { 
    id: 93, 
    title: "Workshop: Mosaic Art for Beginners", 
    desc: "Khóa học nghệ thuật mosaic cho người mới",
    category: "Hội thảo & Workshop",
    date: "2026-05-07", 
    time: "09:00", 
    location: "Creative Lab", 
    color: "bg-orange-500", 
    price: "420.000đ",
    hot: false,
  },
  { 
    id: 94, 
    title: "Saigon Craft Beer Festival", 
    desc: "Lễ hội bia thủ công Sài Gòn",
    category: "Ẩm thực & Đồ uống",
    date: "2026-05-15", 
    time: "17:00", 
    location: "Quận 1", 
    color: "bg-yellow-700", 
    price: "250.000đ",
    hot: false,
  },
  { 
    id: 95, 
    title: "Workshop: Creative Writing 101", 
    desc: "Khóa học viết sáng tạo cơ bản",
    category: "Hội thảo & Workshop",
    date: "2026-05-07", 
    time: "18:00", 
    location: "Book Cafe", 
    color: "bg-blue-200", 
    price: "150.000đ",
    hot: false,
  },
  { 
    id: 96, 
    title: "VPBank Midnight Run Hoàn Kiếm", 
    desc: "Chạy đêm tại hồ Hoàn Kiếm",
    category: "Thể thao",
    date: "2026-05-07", 
    time: "23:00",
    location: "Bờ Hồ Hoàn Kiếm", 
    color: "bg-lime-400", 
    price: "750.000đ",
    hot: false,
  },
  { 
    id: 92, 
    title: "Đêm nhạc Jazz Mùa hạ: Sunny", 
    desc: "Đêm nhạc Jazz Mùa hạ với sự tham gia của nhiều nghệ sĩ jazz nổi tiếng",
    category: "Nhạc sống",
    date: "2026-05-30", time: "20:30", 
    location: "Bình Minh Jazz Club", 
    color: "bg-gray-800", 
    price: "450.000đ",
    hot: false, 
  },
  { 
    id: 93, 
    title: "Workshop: Mosaic Art for Beginners",
    desc: "Khóa học nghệ thuật mosaic dành cho người mới bắt đầu",
    category: "Hội thảo & Workshop", 
    date: "2026-05-07", 
    time: "09:00", 
    location: "Creative Lab", 
    color: "bg-orange-500", 
    price: "420.000đ",
    hot: false, 
  },
  { 
    id: 94, 
    title: "Saigon Craft Beer Festival", 
    desc: "Lễ hội bia thủ công tại Sài Gòn với nhiều loại bia độc đáo",
    category: "Ẩm thực & Đồ uống",
    date: "2026-05-15", 
    time: "17:00", 
    location: "Quận 1", 
    color: "bg-yellow-700", 
    price: "250.000đ",
    hot: false, 
  },
  { 
    id: 95, 
    title: "Workshop: Creative Writing 101", 
    desc: "Khóa học viết sáng tạo cơ bản",
    category: "Hội thảo & Workshop",
    date: "2026-05-07", 
    time: "18:00", 
    location: "Book Cafe", 
    color: "bg-blue-200", 
    price: "150.000đ",
    hot: false,
  },
  { 
    id: 96, 
    title: "VPBank Midnight Run Hoàn Kiếm", 
    desc: "Chạy đêm tại hồ Hoàn Kiếm",
    category: "Thể thao",
    date: "2026-05-07", 
    time: "23:00", 
    location: "Bờ Hồ Hoàn Kiếm", 
    color: "bg-lime-400", 
    price: "750.000đ",
    hot: false, 
  },
  { 
    id: 97, 
    title: "Seminar: Web3 & Metaverse Strategy", 
    desc: "Hội thảo về chiến lược Web3 và Metaverse", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-18", 
    time: "09:00", 
    location: "VNU-IS Building", 
    color: "bg-violet-700", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 98, 
    title: "Workshop: Textile Design - Vẽ trên vải", 
    desc: "Khóa học thiết kế vải và vẽ tranh trên vải", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-04", 
    time: "14:30", 
    location: "Tiệm May Nghệ Thuật", 
    color: "bg-cyan-300", 
    price: "280.000đ",
    hot: false,
  },
  { 
    id: 99, 
    title: "Show: Xiếc Nghệ Thuật 'Làng Tôi'", 
    desc: "Buổi biểu diễn xiếc nghệ thuật 'Làng Tôi'", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-28", 
    time: "19:00", 
    location: "Rạp xiếc Trung ương", 
    color: "bg-red-700", 
    price: "200.000đ",
    hot: false,
  },
  { 
    id: 100, 
    title: "Hội chợ Đồ chơi & Trải nghiệm Kid", 
    desc: "Hội chợ đồ chơi và trải nghiệm dành cho trẻ em", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-31", 
    time: "09:00", 
    location: "Cung Thiếu Nhi Hà Nội", 
    color: "bg-blue-400", 
    price: "Miễn phí",
    hot: false, 
  },
  { 
    id: 103, 
    title: "Workshop: Night Makeup Look", 
    desc: "Khóa học trang điểm đêm", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-08", 
    time: "18:00", 
    location: "Makeup Academy", 
    color: "bg-pink-500", 
    price: "350.000đ",
    hot: false,
  },
  { 
    id: 104, 
    title: "Lễ hội Diều Quốc tế Sông Hồng", 
    desc: "Lễ hội diều quốc tế trên sông Hồng", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-01", 
    time: "15:00", 
    location: "Bãi giữa Sông Hồng", 
    color: "bg-sky-500", 
    price: "Miễn phí",
    hot: false,
  },
  { 
    id: 105, 
    title: "Workshop: Podcast Production 101", 
    desc: "Khóa học sản xuất podcast cơ bản", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-24", 
    time: "14:00", 
    location: "Studio Hub", 
    color: "bg-rose-600", 
    price: "300.000đ",
    hot: false, 
  },
  { 
    id: 106, 
    title: "Giao hưởng: Thu quyến rũ", 
    desc: "Buổi giao hưởng mùa thu quyến rũ", 
    category: "Hội thảo & Workshop", 
    date: "2026-05-10", 
    time: "20:00", 
    location: "Nhà hát Lớn Hà Nội", 
    color: "bg-amber-800", 
    price: "1.000.000đ", 
    hot: false,
  },
  // --- THÁNG 6/2026 ---
  { 
    id: 107, 
    title: "Summer Tech Camp for Student", 
    desc: "Khóa học công nghệ mùa hè cho sinh viên", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-01", 
    time: "08:00", 
    location: "Hòa Lạc Hi-Tech Park", 
    color: "bg-blue-600", 
    price: "2.500.000đ" 
  },
  { 
    id: 108, 
    title: "International Children's Day Fest", 
    desc: "Lễ hội ngày trẻ em quốc tế", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-01", 
    time: "16:00", 
    location: "Công viên Thủ Lệ", 
    color: "bg-pink-400", 
    price: "Miễn phí" 
  },
  { 
    id: 109, 
    title: "Workshop: NFT Strategy for Artists", 
    desc: "Khóa học chiến lược NFT cho nghệ sĩ", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-03", 
    time: "14:00", 
    location: "VNU-IS Hall", 
    color: "bg-indigo-500", 
    price: "Miễn phí" 
  },
  { 
    id: 110, 
    title: "Music Show: Summer Hit Countdown", 
    desc: "Buổi biểu diễn âm nhạc mùa hè", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-05", 
    time: "19:30", 
    location: "Phố đi bộ Hồ Gươm", 
    color: "bg-orange-500", 
    price: "Vào cửa tự do" 
  },
  { 
    id: 111, 
    title: "The Color Run Vietnam 2026", 
    desc: "Cuộc thi chạy màu Việt Nam 2026", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-07", 
    time: "06:00", 
    location: "Khu đô thị Sala", 
    color: "bg-fuchsia-500", 
    price: "350.000đ" 
  },
  { 
    id: 112, 
    title: "Workshop: Video Editing for TikTok", 
    desc: "Khóa học biên tập video cho TikTok", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-08", 
    time: "18:30", 
    location: "Online via Zoom", 
    color: "bg-black", 
    price: "150.000đ" 
  },
  { 
    id: 113, 
    title: "Triển lãm: Food & Hotel Vietnam", 
    desc: "Triển lãm thực phẩm và khách sạn Việt Nam", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-10", 
    time: "09:00", 
    location: "SECC Quận 7", 
    color: "bg-emerald-600", 
    price: "100.000đ" 
  },
  { 
    id: 114, 
    title: "Hội thảo: Crypto Mastery for Gen Z", 
    desc: "Hội thảo về kỹ năng crypto cho thế hệ Gen Z", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-12", 
    time: "15:00", 
    location: "Hội sở MB Bank", 
    color: "bg-yellow-600", 
    price: "Miễn phí" 
  },
  { 
    id: 115, 
    title: "Workshop: Ceramic Art & Craft", 
    desc: "Khóa học nghệ thuật và thủ công gốm sứ", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-13", 
    time: "09:30", 
    location: "Tiệm Gốm Nhà Mình", 
    color: "bg-stone-400", 
    price: "400.000đ" 
  },
  { 
    id: 116, 
    title: "Giải Bóng đá Summer Cup VNU", 
    desc: "Giải bóng đá mùa hè VNU", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-14", time: "16:30", 
    location: "Sân bóng cỏ nhân tạo", 
    color: "bg-green-600", 
    price: "Miễn phí", 
  },
  { 
    id: 118, 
    title: "Workshop: Design Thinking Bootcamp", 
    desc: "Khóa học tư duy thiết kế", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-18", 
    time: "09:00", 
    location: "Dreamplex Coworking", 
    color: "bg-cyan-500", 
    price: "300.000đ", 
  },
  { 
    id: 119, 
    title: "Bảo tàng chiêm tinh học", 
    desc: "Triển lãm chiêm tinh học", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-19", 
    time: "08:00", 
    location: "Hoà Lạc, Hà Nội", 
    color: "bg-amber-500", 
    price: "150.000đ", 
  }, // Giữ nguyên
  { 
    id: 120, 
    title: "Trải nghiệm: Chèo Sup ngắm bình minh", 
    desc: "Trải nghiệm chèo sup ngắm bình minh", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-21", 
    time: "05:00", 
    location: "Hồ Tây", 
    color: "bg-sky-400", 
    price: "250.000đ", 
  },
  { 
    id: 124, 
    title: "Workshop: Natural Skincare DIY", 
    desc: "Khóa học chăm sóc da tự nhiên", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-27", 
    time: "10:00", 
    location: "Lab Studio", 
    color: "bg-rose-300", 
    price: "450.000đ" 
  },
  { 
    id: 125, 
    title: "Hội chợ: Thai Consumer Expo 2026", 
    desc: "Hội chợ tiêu dùng Thái Lan 2026", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-28", 
    time: "08:30", 
    location: "Trung tâm Triển lãm", 
    color: "bg-red-400", 
    price: "Miễn phí" 
  },
  { 
    id: 126, 
    title: "Workshop: Personal Finance 101", 
    desc: "Khóa học tài chính cá nhân cơ bản", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-30", 
    time: "18:00", 
    location: "VNU Library Hall", 
    color: "bg-indigo-700", 
    price: "Miễn phí" 
  },
  { 
    id: 127, 
    title: "Lớp học: Bơi sải nâng cao", 
    desc: "Lớp học bơi sải nâng cao", 
    category: "Hội thảo & Workshop", 
    date: "2026-06-02", 
    time: "06:00", 
    location: "Bể bơi Mỹ Đình", 
    color: "bg-blue-300", 
    price: "200.000đ" 
  },
  { 
    id: 128, 
    title: "Workshop: Modern Acrylic Painting", 
    desc: "Khóa học vẽ acrylic hiện đại", 
    category: "Hội thảo & Workshop", 
    date:  "2026-06-06", time: "14:30",
    location: "Canvas Studio", 
    color: "bg-yellow-400", 
    price: "320.000đ", 
  },
  { 
    id: 130, 
    title: "Khóa học: Yoga Harmony Summer", 
    desc: "Khóa học yoga mùa hè", 
    category: "Hội thảo & Workshop",
    date: "2026-06-15", time: "17:30", 
    location: "CLB Sức Sống Mới", 
    color: "bg-green-400", 
    price: "800.000đ",
  },
  { 
    id: 131, 
    title: "Hội thảo: Generative AI in Art", 
    desc: "Hội thảo về AI tạo sinh trong nghệ thuật", 
    category: "Hội thảo & Workshop",
    date: "2026-06-23", time: "14:00", 
    location: "Bảo tàng Mỹ thuật", 
    color: "bg-stone-800",
    price: "100.000đ",
  },
  { 
    id: 132, 
    title: "Workshop: Basic PC Build & Fix", 
    desc: "Khóa học lắp ráp và sửa chữa PC cơ bản", 
    category: "Hội thảo & Workshop",
    date: "2026-06-25", 
    time: "09:00", 
    location: "VNU IT Center", 
    color: "bg-zinc-500", 
    price: "Miễn phí" 
  },
  { 
    id: 133, 
    title: "Giao hưởng: Giai điệu mùa hạ", 
    desc: "Buổi giao hưởng với chủ đề giai điệu mùa hạ", 
    category: "Hội thảo & Workshop",
    date: "2026-06-29", 
    time: "20:00", 
    location: "Nhà hát Kịch Hà Nội", 
    color: "bg-amber-900", 
    price: "300.000đ" 
  },
  { 
    id: 134, 
    title: "Giải chạy: Sức Trẻ Việt Nam", 
    desc: "Giải chạy dành cho thanh niên Việt Nam", 
    category: "Hội thảo & Workshop",
    date: "2026-06-04", 
    time: "05:30", 
    location: "Công viên Yên Sở", 
    color: "bg-emerald-400", 
    price: "Miễn phí" 
  },
  { 
    id: 135, 
    title: "Workshop: iPhone Photography Tour", 
    desc: "Khóa học chụp ảnh bằng iPhone", 
    category: "Hội thảo & Workshop",
    date:  "2026-06-11", 
    time: "15:00", 
    location: "Đường Phan Đình Phùng", 
    color: "bg-gray-700", 
    price: "200.000đ" 
  },
  { 
    id: 136, 
    title: "Hội thảo: Du học Châu Âu 2026", 
    desc: "Hội thảo về du học Châu Âu", 
    category: "Hội thảo & Workshop",
    date: "2026-06-17", 
    time: "08:30", 
    location: "Khách sạn Pullman", 
    color: "bg-blue-800", 
    price: "Miễn phí" 
  },
  // --- THÁNG 7/2026 ---
  { 
    id: 137, 
    title: "8Wonder Summer: World Class Music", 
    desc: "Lễ hội âm nhạc đẳng cấp thế giới", 
    category: "Nhạc sống",
    date: "2026-07-01", time: "19:00", 
    location: "VinWonders Nha Trang", 
    color: "bg-red-500", 
    price: "800.000đ", 
  },
  { 
    id: 138, 
    title: "Live Acoustic: Chuyện của Nắng", 
    desc: "Buổi biểu diễn acoustic với chủ đề Chuyện của Nắng", 
    category: "Nhạc sống",
    date: "2026-07-03", 
    time: "20:30", 
    location: "Lululola Coffee+", 
    color: "bg-orange-400", 
    price: "350.000đ",
  },
  { 
    id: 139, 
    title: "Trải nghiệm: Làng Gốm Bát Tràng Tour", 
    desc: "Trải nghiệm với làng gốm Bát Tràng", 
    category: "Tham quan & Trải nghiệm",
    date: "2026-07-04", 
    time: "09:00", 
    location: "Bát Tràng, Hà Nội", 
    color: "bg-stone-500", 
    price: "450.000đ",
  },
  { 
    id: 140, 
    title: "Summer Splash Swim Championship", 
    desc: "Giải bơi mùa hè", 
    category: "Thể thao",
    date: "2026-07-05", 
    time: "07:30", 
    location: "Cung dưới nước", 
    color: "bg-blue-400", 
    price: "150.000đ", 
  },
  { 
    id: 141, 
    title: "Jazz Night: Midnight Blues", 
    desc: "Đêm nhạc jazz với chủ đề Midnight Blues", 
    category: "Nhạc sống",
    date: "2026-07-07", 
    time: "21:00", 
    location: "Bình Minh Jazz Club", 
    color: "bg-indigo-900", 
    price: "500.000đ",
  },
  { 
    id: 142, 
    title: "Tour: Địa đạo Củ Chi - Di sản thép", 
    desc: "Tour tham quan địa đạo Củ Chi", 
    category: "Tham quan & Trải nghiệm",
    date: "2026-07-10", 
    time: "08:00", 
    location: "Củ Chi, TP.HCM", 
    color: "bg-emerald-700", 
    price: "600.000đ", 
  },
  { 
    id: 143, 
    title: "Workshop: Vẽ tranh En Plein Air", 
    date: "2026-07-11", 
    time: "16:00", 
    location: "Công viên Yên Sở", 
    color: "bg-teal-400", 
    price: "300.000đ",
  },
  { 
    id: 144, 
    title: "Rock Concert: Lửa Mùa Hè 2026", 
    date: "2026-07-12", 
    time: "19:00", 
    location: "Nhà thi đấu Phú Thọ", 
    color: "bg-gray-900", 
    price: "400.000đ" 
  },
  { 
    id: 145, 
    title: "Giải Tennis VNU Open 2026", 
    desc: "Giải tennis mở rộng VNU", 
    category: "Thể thao",
    date: "2026-07-14", 
    time: "08:00", 
    location: "Cụm sân Tennis VNU", 
    color: "bg-lime-500", 
    price: "Miễn phí", 
  },
  { 
    id: 146, 
    title: "Workshop: Mixology - Cocktail Art", 
    desc: "Khóa học pha chế cocktail", 
    category: "Hội thảo & Workshop",
    date: "2026-07-15", 
    time: "18:00", 
    location: "The Alchemist Bar", 
    color: "bg-pink-600", 
    price: "550.000đ", 
  },
  {
    id: 147, 
    title: "Hard Rock Indie Night: Vol 1", 
    desc: "Đêm nhạc hard rock indie", 
    category: "Nhạc sống",
    date: "2026-07-17", 
    time: "20:00", 
    location: "Hard Rock Cafe", 
    color: "bg-fuchsia-700", 
    price: "250.000đ", 
  },
  { 
    id: 148, 
    title: "Streetball Championship 3x3", 
    desc: "Giải bóng rổ đường phố", 
    category: "Thể thao",
    date: "2026-07-18", 
    time: "17:00", 
    location: "Sân bóng rổ ĐH Y", 
    color: "bg-orange-600", 
    price: "Miễn phí", 
  },
  { 
    id: 149, 
    title: "Tour đêm: Sống lại hào khí Hỏa Lò", 
    desc: "Tour tham quan di tích Hỏa Lò", 
    category: "Tham quan & Trải nghiệm",
    date: "2026-07-19", 
    time: "19:30", 
    location: "Di tích Hỏa Lò", 
    color: "bg-zinc-800", 
    price: "300.000đ", 
  },
  { 
    id: 150, 
    title: "Workshop: Modern Hand Embroidery",
    desc: "Khóa học thêu tay hiện đại",
    category: "Hội thảo & Workshop", 
    date: "2026-07-21", 
    time: "14:00", 
    location: "Tiệm Thêu Tay", 
    color: "bg-rose-300", 
    price: "280.000đ",
  },
  { 
    id: 151, 
    title: "Đêm nhạc Trịnh: Hạ Trắng & Mưa",
    desc: "Đêm nhạc Trịnh: Hạ Trắng & Mưa",
    category: "Nhạc sống",
    date: "2026-07-22", 
    time: "20:00", 
    location: "Phòng trà Đồng Dao", 
    color: "bg-amber-700", 
    price: "450.000đ", 
  },
  { 
    id: 152, 
    title: "Run for Love: Hanoi Summer Race",
    desc: "Cuộc đua vì tình yêu tại Hà Nội mùa hè",
    category: "Thể thao",
    date: "2026-07-24", 
    time: "04:30", 
    location: "Hồ Tây", 
    color: "bg-sky-500", 
    price: "500.000đ", 
  },
  { 
    id: 153, 
    title: "Workshop: Terrarium Art Design",
    desc: "Khóa học thiết kế nghệ thuật terrarium",
    category: "Hội thảo & Workshop", 
    date: "2026-07-25", 
    time: "10:00", 
    location: "Green Oasis Lab", 
    color: "bg-green-600", 
    price: "420.000đ", 
  },
  { 
    id: 154, 
    title: "Acoustic Beach Party: Vũng Tàu",
    desc: "Bữa tiệc âm nhạc acoustic trên bãi biển Vũng Tàu",
    category: "Nhạc sống", 
    date: "2026-07-26", 
    time: "19:00", 
    location: "Beach Club Vũng Tàu", 
    color: "bg-cyan-400", 
    price: "300.000đ", 
  },
  { 
    id: 155, 
    title: "Giải Cầu lông Cầu Giấy mở rộng",
    desc: "Giải cầu lông mở rộng tại Cầu Giấy",
    category: "Thể thao",
    date: "2026-07-28", 
    time: "08:00", 
    location: "Nhà thi đấu Cầu Giấy", 
    color: "bg-yellow-500", 
    price: "100.000đ",
  },
  { 
    id: 156, 
    title: "Workshop: Scented Candle Making", 
    desc: "Khóa học làm nến thơm",
    category: "Hội thảo & Workshop",
    date: "2026-07-29", 
    time: "15:00", 
    location: "The Candle Shop", 
    color: "bg-violet-400", 
    price: "380.000đ",
  },
  {
    id: 157,
    title: "Triển lãm Harry Potter: Trải nghiệm phép thuật",
    desc: "Triển lãm phép thuật",
    category: "Tham quan & Trải nghiệm",
    date: "2026-07-31",
    location: "Bảo tàng Harry Potter",
    price: "200.000đ",
    hot: true,
    img: "harrypotter.jpeg",
  }, // Giữ nguyên
  {
    id: 158,
    title: "Bảo tàng chiêm tinh học",
    desc: "Khám phá vũ trụ",
    category: "Tham quan & Trải nghiệm",
    date: "2026-06-19",
    location: "Hòa Lạc, Hà Nội",
    price: "150.000đ",
    hot: true,
    img: "chiemtinh.jpeg"
  },
];

// ===== RENDER =====
function renderEvents(filter = "all") {
  let list = document.getElementById("eventList");
  list.innerHTML = "";

  let filtered = events.filter(e =>
    filter === "all" || e.category === filter
  );

  filtered.forEach(e => {
    list.innerHTML += `
      <div class="card" onclick="goToanhtraisayhi('${e.title}', '${e.date}','${e.location}', '${e.price}', '${e.img}')">
        <div class="card-img">
          <img src="${e.img}">
          ${e.hot ? `<div class="tag">HOT</div>` : ""}
        </div>
        <div class="info">
          <h4>${e.title}</h4>
          <div class="meta">${e.date} • ${e.location}</div>
          <div class="bottom">
            <span class="price">${e.price}</span>
            <button class="buy-btn">Mua vé</button>
          </div>
        </div>
      </div>
    `;
  });

filtered.forEach(e => {
  list.innerHTML += `
    <div class="card" onclick="handleClick(${e.id})">
      
      <div class="card-img">
        <img src="${e.img}">
        ${e.hot ? `<div class="tag">HOT</div>` : ""}
      </div>

      <div class="info">
        <h4>${e.title}</h4>
        <div class="meta">${e.date} • ${e.location}</div>

        <div class="bottom">
          <span class="price">${e.price}</span>
          <button class="buy-btn" onclick="event.stopPropagation()">Mua vé</button>
        </div>

      </div>
    </div>
  `;
});
}

// ===== HOT =====
// --- Cập nhật lại logic Render ---
function renderEvents(filter = "all") {
  let list = document.getElementById("eventList");
  if (!list) return;
  list.innerHTML = "";

  // Lọc danh sách theo category
  let filtered = events.filter(e =>
    filter === "all" || e.category === filter
  );

  filtered.forEach(e => {
    // Chỉ render 1 lần duy nhất mỗi card
    list.innerHTML += `
      <div class="card" onclick="handleClick(${e.id})">
        <div class="card-img">
          <img src="${e.img}" onerror="this.src='https://via.placeholder.com/400x200'">
          ${e.hot ? `<div class="tag">HOT</div>` : ""}
        </div>
        <div class="info">
          <h4>${e.title}</h4>
          <div class="meta">${e.date} • ${e.location}</div>
          <div class="bottom">
            <span class="price">${e.price}</span>
            <button class="buy-btn" onclick="handleBuyClick(event, ${e.id})">Mua vé</button>
          </div>
        </div>
      </div>
    `;
  });
}

// --- Hàm xử lý khi nhấn nút "Mua vé" ---
function handleBuyClick(event, id) {
  event.stopPropagation(); // Ngăn sự kiện click lan ra thẻ card (tránh mở Modal)
  
  let selectedEvent = events.find(ev => ev.id === id);
  if (!selectedEvent) return;

  // KIỂM TRA: Nếu sự kiện có file riêng (như index.html của 30/4)
  if (selectedEvent.file) {
    window.location.href = selectedEvent.file; // Nhảy sang trang intro con rồng
  } else {
    // Nếu không có file intro, nhảy sang trang đặt vé mặc định
    // Truyền ID qua URL để trang sau biết đang mua vé cho sự kiện nào
    window.location.href = `anhtraisayhi.html?id=${id}`;
  }
}

// --- Hàm xử lý khi nhấn vào bất kỳ đâu trên card (trừ nút mua vé) ---
function handleClick(id) {
  let selectedEvent = events.find(ev => ev.id === id);
  if (!selectedEvent) return;

  // Nếu là sự kiện 30/4, nhấn vào hình cũng cho xem intro luôn
  if (selectedEvent.file) {
    window.location.href = selectedEvent.file;
  } else {
    // Hiện modal thông tin chi tiết như cũ
    openDetail(selectedEvent.title, selectedEvent.desc || "Không có mô tả chi tiết.");
  }
}

// Đảm bảo gọi lại hàm khởi tạo
renderEvents();
renderHot();

// 1. Sửa hàm handleClick: Nhấn vào đâu trên card cũng chạy intro nếu có
function handleClick(id) {
  let e = events.find(ev => ev.id === id);
  if (!e) return;

  if (e.file) {
    // Nếu có intro (như sự kiện 30/4), chuyển đến index.html
    window.location.href = e.file;
  } else {
    // Event bình thường thì mở modal chi tiết
    openDetail(e.title, e.desc || "Không có mô tả");
  }
}

// 2. Bổ sung hàm handleBuyClick: Đảm bảo nút "Mua vé" hoạt động
function handleBuyClick(event, id) {
  event.stopPropagation(); // Ngăn việc mở modal chi tiết khi nhấn nút
  let e = events.find(ev => ev.id === id);
  if (!e) return;

  if (e.file) {
    // Nhấn "Mua vé" của sự kiện 30/4 cũng dẫn vào intro trước
    window.location.href = e.file;
  } else {
    // Các sự kiện khác nhảy thẳng tới trang đặt vé
    window.location.href = "anhtraisayhi.html";
  }
}